# Generated by Django 4.0.4 on 2022-04-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('point_de_depart', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('altitude_de_depart', models.IntegerField(verbose_name='altitude (m)')),
                ('altitude_min', models.IntegerField(verbose_name='altitude (m)')),
                ('altitude_max', models.IntegerField(verbose_name='altitude (m)')),
                ('denivele_positif_cumule', models.FloatField(default=0)),
                ('denivele_negatif_cumule', models.FloatField(default=0)),
                ('duree_estimee', models.FloatField(verbose_name='Duree estimee (h)')),
                ('difficulte_estimee', models.IntegerField(verbose_name='Difficulte')),
            ],
        ),
        migrations.CreateModel(
            name='sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=200)),
                ('date_de_sortie', models.DateTimeField(verbose_name='date de sortie')),
                ('duree_reelle', models.FloatField(verbose_name='Duree reelle (h)')),
                ('nombre_de_personne', models.IntegerField(verbose_name='le nombre de personnes ayant participe à la sortie')),
                ('experience', models.CharField(max_length=200)),
                ('meteo', models.CharField(max_length=200)),
                ('difficulte', models.IntegerField(verbose_name='la difficulté ressentie')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
            ],
        ),
    ]
