# Generated by Django 4.0.4 on 2022-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='commentaire',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='description',
            field=models.TextField(),
        ),
    ]
